In [1]:
import pandas as pd

In [79]:
# Dictionary with the purpose of reducing memory size when loading the dataset.
dict_tipos = {
# SIMAT
'ANO_INF':              'uint16',
'CODIGO_DANE':          'uint64',
'CODIGO_DANE_SEDE':     'uint64',
'TIPO_DOCUMENTO':       'uint8',
'NRO_DOCUMENTO':        'string',
'DIRECCION_RESIDENCIA': 'string',
'RES_DEPTO':            'uint8',
'RES_MUN':              'uint16',
'ESTRATO':              'uint8',
'SISBEN':               'float16',
'GENERO':               'uint8',
'POB_VICT_CONF':        'uint8',
'PROVIENE_SECTOR_PRIV': 'uint8',
'PROVIENE_OTR_MUN':     'uint8',
'TIPO_DISCAPACIDAD':    'uint8',
'CAP_EXC':              'uint8',
'CODIGO_ETNIA':         'uint16',
'CODIGO_JORNADA':       'uint8',
'CARACTER':             'uint8',
'CODIGO_ESPECIALIDAD':  'uint8',
'CODIGO_GRADO':         'int8',
'CODIGO_METODOLOGIA':   'uint8',
'REPITENTE':            'uint8',
'SIT_ACAD_ANIO_ANT':    'uint8',
'CON_ALUM_ANIO_ANT':    'uint8',
'ZONA_RESI_ALU':        'uint8',
'EDAD':                 'uint8',
'NIVEL':                'uint8',
'DIR_NUM_LOCALIDAD':    'uint8',
'NIVEL_SISBEN':         'uint8',
'GRADO_OVERAGE':        'uint8',
'OVERAGE':              'uint8',
# SISBEN
'ficha':                'int64',
'comuna':               'uint8',
'barrio':               'uint32',
'nombarrio':            'string',
'direcc':               'string',
'vereda':               'uint8',
'nomvereda':            'string',
'vivienda':             'uint8',
'pared':                'uint8',
'piso':                 'uint8',
'energia':              'uint8',
'alcanta':              'uint8',
'gas':                  'uint8',
'telefono' :            'uint8',
'basura' :              'uint8',
'acueduc' :             'uint8',
'estrato' :             'uint8',
'elimbasura' :          'uint8',
'tcuartosvi' :          'uint8',
'thogar' :              'uint8',
'recolec' :             'uint8',
'tipdir' :              'uint8',
'verifica' :            'uint8',
'hogar' :               'uint8',
'teneviv' :             'uint8',
'tcuartos' :            'uint8',
'tdormir' :             'uint8',
'sanitar' :             'uint8',
'usanitar' :            'uint8',
'usosani' :             'uint8',
'tsanitar' :            'uint8',
'ducha' :               'uint8',
'agua' :                'uint8',
'llega' :               'uint8',
'cuandi' :              'uint8',
'suminis' :             'uint8',
'cuanhoras' :           'uint8',
'preparan' :            'uint8',
'cocina' :              'uint8',
'cocinan' :             'uint8',
'alumbra' :             'uint8',
'usotele' :             'uint8',
'nevera' :              'uint8',
'lavadora' :            'uint8',
'tvcolor' :             'uint8',
'tvcable' :             'uint8',
'calenta' :             'uint8',
'horno' :               'uint8',
'aire' :                'uint8',
'computador' :          'uint8',
'equipo' :              'uint8',
'moto' :                'uint8',
'tractor' :             'uint8',
'tiene_auto' :          'uint8',
'bieraices':            'uint8',
'tpersona' :            'uint8',
'informan' :            'uint8',
'orden' :               'uint8',
'nucleo' :              'uint8',
'parentes' :            'uint8',
'tipodoc' :             'uint8',
'documen':              'string',
'sexo' :                'uint8',
'estcivil' :            'uint8',
'discapa' :             'uint8',
'carnet' :              'uint8',
'asiste' :              'uint8',
'tipoesta' :            'uint8',
'grado' :               'uint8',
'nivel' :               'uint8',
'activi' :              'uint8',
'buscando' :            'uint8',
'ingresos':             'int64',
'edad':                 'uint8',
'conyuvive':            'uint8',
'hijosde':              'int8',
'embaraza' :            'uint8',
'extranjero' :          'uint8',
'pagapor' :             'uint8',
'percibe' :             'uint8',
'serdomes' :            'uint8',
'unigasto' :            'uint8',
'area' :                'uint8',
'nparentes':            'uint8',
'puntaje_sisben_3':     'float32',
'todos_servicios_Pub':  'uint8',
'indice_hacinamiento':  'float16',
# C-600  
'ES_BILIGUE':           'int8',
'TOTAL_DOCENTES':       'uint16',
'TOTAL_ALUMNOS':        'uint16',
'TOTAL_EQUIPO_COMPUTO': 'uint16',
'TOTAL_DOCENTES_CON_TITULO':'uint8',
# ICFES
'num_presentaron_ICFES': 'uint8'
  }

In [34]:
df_2020 = pd.read_csv('data/3-oro/Merge_2020_ICFES_C600.csv' , index_col=0, dtype = dict_tipos)

In [35]:
df_2019 = pd.read_csv('data/3-oro/Merge_2019_ICFES_C600.csv', index_col = 0 , dtype = dict_tipos)

In [36]:
df =  pd.concat([df_2019, df_2020], axis=0)

In [37]:
df

,ANO_INF,CODIGO_DANE,CODIGO_DANE_SEDE,TIPO_DOCUMENTO,NRO_DOCUMENTO,DIRECCION_RESIDENCIA,RES_DEPTO,RES_MUN,ESTRATO,SISBEN,...,ES_BILINGUE,TOTAL_DOCENTES,TOTAL_ALUMNOS,TOTAL_EQUIPO_COMPUTO,ALUMN_POR_DOCENTE,COMPU_POR_ALUMN,TOTAL_DOCENTES_CON_TITULO,PROP_DOCENTES_CON_TITULO,promepuntaje,num_presentaron_ICFES
0,2019,111001000078,111001000078,5,1000003730,CR 51 D # 35 SUR - 45,11,1,3,43.0,...,0,29,561,319,19.344828,0.568627,28,0.965517,265.478873,71
1,2019,111001000078,111001000078,2,1000004716,CL 29 A SUR # 50 - 41 PL 2,11,1,3,29.0,...,0,29,561,319,19.344828,0.568627,28,0.965517,265.478873,71
2,2019,111001000078,111001000078,7,1000007657,CL 28 SUR # 51 F - 81,11,1,3,46.0,...,0,29,561,319,19.344828,0.568627,28,0.965517,265.478873,71
3,2019,111001000078,111001000078,5,1000008029,CL 32 SUR # 46 - 84 86,11,1,3,30.0,...,0,29,561,319,19.344828,0.568627,28,0.965517,265.478873,71
4,2019,111001000078,111001000078,2,1000033547,KR 35 A 1 H 32,11,1,2,0.0,...,0,29,561,319,19.344828,0.568627,28,0.965517,265.478873,71
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457042,2020,311001107629,311001107629,2,1026256645,CL 77 45 A 03 SUR,11,1,1,72.0,...,0,19,457,84,24.052632,0.183807,7,0.368421,310.571429,21
457043,2020,311001107629,311001107629,2,1016595384,TV 65 77 54 SUR PI 1,11,1,1,53.0,...,0,19,457,84,24.052632,0.183807,7,0.368421,310.571429,21
457044,2020,311001107629,311001107629,2,1024477229,CL 69 H SUR 48 B 22,11,1,1,30.0,...,0,19,457,84,24.052632,0.183807,7,0.368421,310.571429,21
457045,2020,311001107629,311001107629,2,1029141941,KR 73 H 76 A 40 SUR,11,1,1,62.0,...,0,19,457,84,24.052632,0.183807,7,0.368421,310.571429,21
457046,2020,311001107629,311001107629,2,1033690026,KR 45 C 73 B 14 SUR,11,1,1,50.0,...,0,19,457,84,24.052632,0.183807,7,0.368421,310.571429,21

In [38]:
variables = ['EDAD',
             'estrato',
             'puntaje_sisben_3',
             'indice_hacinamiento', #-> solo si no se pone nivel_hacinamiento en Categoria
             'TOTAL_EQUIPO_COMPUTO',
             'ALUMN_POR_DOCENTE',
             'COMPU_POR_ALUMN',
             'TOTAL_DOCENTES_CON_TITULO',
             'PROP_DOCENTES_CON_TITULO', #-> solo si no se incluye TOTAL_DOCENTES_CON_TITULO y TOTAL_ALUM al tiempo
             'promepuntaje',
             'GRADO_OVERAGE',
             'CODIGO_GRADO',
             #'TOTAL_DOCENTES',
             #'TOTAL_ALUMNOS',
             'nparentes',
             #'tcuartosvi',
             'tpersona'
            ]

In [39]:
categorias= ['GENERO',
             'POB_VICT_CONF',
             'PROVIENE_OTR_MUN',
             'TIPO_DISCAPACIDAD',
             'CODIGO_ETNIA',
             'CODIGO_JORNADA',
             'DIR_NUM_LOCALIDAD',
             'embaraza',
             'todos_servicios_Pub',
             'teneviv',
             'computador',
             'tiene_auto',
             'ES_BILINGUE',
             'CAP_EXC',
             'NIVEL',
             'CODIGO_METODOLOGIA',
             'ANO_INF',
             'REPITENTE'
             ]

In [40]:
df = df[variables + categorias]

In [41]:
df

,EDAD,estrato,puntaje_sisben_3,indice_hacinamiento,TOTAL_EQUIPO_COMPUTO,ALUMN_POR_DOCENTE,COMPU_POR_ALUMN,TOTAL_DOCENTES_CON_TITULO,PROP_DOCENTES_CON_TITULO,promepuntaje,...,todos_servicios_Pub,teneviv,computador,tiene_auto,ES_BILINGUE,CAP_EXC,NIVEL,CODIGO_METODOLOGIA,ANO_INF,REPITENTE
0,16,3,43.919998,2.500000,319,19.344828,0.568627,28,0.965517,265.478873,...,1,1,0,0,0,9,4,1,2019,0
1,15,3,29.440001,2.500000,319,19.344828,0.568627,28,0.965517,265.478873,...,1,1,0,0,0,9,3,1,2019,0
2,15,3,46.810001,3.000000,319,19.344828,0.568627,28,0.965517,265.478873,...,1,1,0,0,0,9,4,1,2019,0
3,16,3,30.650000,4.000000,319,19.344828,0.568627,28,0.965517,265.478873,...,1,1,1,0,0,9,4,1,2019,0
4,15,2,60.119999,1.333008,319,19.344828,0.568627,28,0.965517,265.478873,...,1,1,0,0,0,9,4,1,2019,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457042,14,1,65.589996,3.000000,84,24.052632,0.183807,7,0.368421,310.571429,...,1,3,1,0,0,9,3,1,2020,0
457043,14,1,53.740002,1.500000,84,24.052632,0.183807,7,0.368421,310.571429,...,1,2,0,0,0,9,3,1,2020,0
457044,14,1,30.570000,2.500000,84,24.052632,0.183807,7,0.368421,310.571429,...,1,1,1,0,0,9,3,1,2020,0
457045,14,1,50.430000,2.666016,84,24.052632,0.183807,7,0.368421,310.571429,...,1,3,1,0,0,9,3,1,2020,0
457046,14,1,50.090000,2.000000,84,24.052632,0.183807,7,0.368421,310.571429,...,1,4,0,0,0,9,3,1,2020,0

In [42]:
for x in categorias:
    print(x , df[x].unique())

GENERO [0 1]
POB_VICT_CONF [99  1  9  2 20  3  4 10  6 18 17 12  7 15  8 21 13]
PROVIENE_OTR_MUN [0 1]
TIPO_DISCAPACIDAD [0 1]
CODIGO_ETNIA [0 2 1 5 4 3 6]
CODIGO_JORNADA [6 2 3 1]
DIR_NUM_LOCALIDAD [16  3 10 18 19  8  7  5 11  6 14  4 15 12  9  1 17  2 13 20]
embaraza [0 1]
todos_servicios_Pub [1 0]
teneviv [1 4 3 2]
computador [0 1]
tiene_auto [0 1]
ES_BILINGUE [0 1]
CAP_EXC [ 9  4  3  1  2  6  5  7 10 11]
NIVEL [4 3 2 1]
CODIGO_METODOLOGIA [ 1  9 11]
ANO_INF [2019 2020]
REPITENTE [0 1]

In [43]:
limpias = []
for x in categorias:
    if set(df[x].unique()) == {0,1}:
        df[x].replace( {0:'No', 1:'Yes'}, inplace = True)
        limpias.append(x)

C:\Users\diego\anaconda3\lib\site-packages\pandas\core\series.py:4509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [44]:
for x in categorias:
    print(x , df[x].unique())

GENERO ['No' 'Yes']
POB_VICT_CONF [99  1  9  2 20  3  4 10  6 18 17 12  7 15  8 21 13]
PROVIENE_OTR_MUN ['No' 'Yes']
TIPO_DISCAPACIDAD ['No' 'Yes']
CODIGO_ETNIA [0 2 1 5 4 3 6]
CODIGO_JORNADA [6 2 3 1]
DIR_NUM_LOCALIDAD [16  3 10 18 19  8  7  5 11  6 14  4 15 12  9  1 17  2 13 20]
embaraza ['No' 'Yes']
todos_servicios_Pub ['Yes' 'No']
teneviv [1 4 3 2]
computador ['No' 'Yes']
tiene_auto ['No' 'Yes']
ES_BILINGUE ['No' 'Yes']
CAP_EXC [ 9  4  3  1  2  6  5  7 10 11]
NIVEL [4 3 2 1]
CODIGO_METODOLOGIA [ 1  9 11]
ANO_INF [2019 2020]
REPITENTE ['No' 'Yes']

In [45]:
faltantes = list(set(categorias) - set(limpias))

In [46]:
faltantes

['CODIGO_ETNIA',
 'NIVEL',
 'teneviv',
 'POB_VICT_CONF',
 'DIR_NUM_LOCALIDAD',
 'ANO_INF',
 'CAP_EXC',
 'CODIGO_METODOLOGIA',
 'CODIGO_JORNADA']

In [47]:
dict_etnia = {
0:  'Not apply',
1 : 'Indigenous',
2 : 'Negritudes',
3 : 'Rom',
4 : 'Raizales',
5 : 'Afro',
6 : 'Palenqueros'
}

df['CODIGO_ETNIA'].replace(dict_etnia, inplace = True)

C:\Users\diego\anaconda3\lib\site-packages\pandas\core\series.py:4509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [49]:
dict_nivel = {
    1 : 'Preschool',
    2 : 'Elementary school',
    3 : 'Middle school',
    4 : 'High school'
}
df['NIVEL'].replace(dict_nivel, inplace = True)

C:\Users\diego\anaconda3\lib\site-packages\pandas\core\series.py:4509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [50]:
dict_vict_recod = {
    99: 0,
    1: 1, 
    10: 1,
    3: 1,
    9: 1,
    4: 1,
    2: 1,
    18: 1,
    17: 1,
    7: 1,
    20: 1,
    6: 1,
    12: 1,
    15: 1,
    8: 1,
    13: 1,
    21: 1
}

In [51]:
df['POB_VICT_CONF'] = df['POB_VICT_CONF'].replace(dict_vict_recod)

<ipython-input-51-fd4534d4d3a8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['POB_VICT_CONF'] = df['POB_VICT_CONF'].replace(dict_vict_recod)

In [53]:
df['POB_VICT_CONF'].replace( {0: 'No', 1:'Yes'} , inplace = True)

C:\Users\diego\anaconda3\lib\site-packages\pandas\core\series.py:4509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [54]:
dict_localidad = {
1 : 'Usaquen',
2 : 'Chapinero',
3 : 'Santa Fe',
4 : 'San Cristobal',
5 : 'Usme',
6  :'Tunjuelito',
7  :'Bosa',
8  :'Kennedy',
9  :'Fontibon',
10 : 'Engativa',
11 : 'Suba',
12 : 'Barrios Unidos',
13 : 'Teusaquillo',
14 : 'Los Martires',
15 : 'Antonio Nariño',
16 : 'Puente Aranda',
17 : 'La Candelaria',
18 : 'Rafael Uribe Uribe',
19 :'Ciudad Bolivar',
20  : 'Sumapaz'
    }
df['DIR_NUM_LOCALIDAD'].replace(dict_localidad, inplace = True)

C:\Users\diego\anaconda3\lib\site-packages\pandas\core\series.py:4509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [55]:
df['CAP_EXC'].unique()

array([ 9,  4,  3,  1,  2,  6,  5,  7, 10, 11], dtype=uint8)

In [56]:
dict_cp_exc ={
1: 'Exceptional capabilities',  
2: 'Other',                                                                                                         
3: 'Science',                                                                            
4: 'Art',
5: 'Sports',
6: 'Double',          
7: 'Social sciences',                     
10: 'Technology', 
11 : 'Leadership',                                                                                              
9 : 'Not apply'
}
df['CAP_EXC'].replace(dict_cp_exc, inplace = True)

C:\Users\diego\anaconda3\lib\site-packages\pandas\core\series.py:4509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [57]:
dict_metodo = {
1: 'Traditional Education',
9:'Accelerating Learning',
10: 'Program for overage youth and adults',
11: 'Schoolized Preschool'
}
df['CODIGO_METODOLOGIA'].replace(dict_metodo, inplace = True)

C:\Users\diego\anaconda3\lib\site-packages\pandas\core\series.py:4509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [58]:
dict_jornada = {
1: 'Complete',
2: 'Morning',
3: 'Afternoon',
4: 'Nocturnal',
5: 'Weekend',
6: 'Unique'
}
df['CODIGO_JORNADA'].replace(dict_jornada, inplace = True)

C:\Users\diego\anaconda3\lib\site-packages\pandas\core\series.py:4509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [59]:
for x in categorias:
    print(x , df[x].unique())

GENERO ['No' 'Yes']
POB_VICT_CONF ['No' 'Yes']
PROVIENE_OTR_MUN ['No' 'Yes']
TIPO_DISCAPACIDAD ['No' 'Yes']
CODIGO_ETNIA ['Not apply' 'Negritudes' 'Indigenous' 'Afro' 'Raizales' 'Rom'
 'Palenqueros']
CODIGO_JORNADA ['Unique' 'Morning' 'Afternoon' 'Complete']
DIR_NUM_LOCALIDAD ['Puente Aranda' 'Santa Fe' 'Engativa' 'Rafael Uribe Uribe'
 'Ciudad Bolivar' 'Kennedy' 'Bosa' 'Usme' 'Suba' 'Tunjuelito'
 'Los Martires' 'San Cristobal' 'Antonio Nariño' 'Barrios Unidos'
 'Fontibon' 'Usaquen' 'La Candelaria' 'Chapinero' 'Teusaquillo' 'Sumapaz']
embaraza ['No' 'Yes']
todos_servicios_Pub ['Yes' 'No']
teneviv [1 4 3 2]
computador ['No' 'Yes']
tiene_auto ['No' 'Yes']
ES_BILINGUE ['No' 'Yes']
CAP_EXC ['Not apply' 'Art' 'Science' 'Exceptional capabilities' 'Other' 'Double'
 'Sports' 'Social sciences' 'Technology' 'Leadership']
NIVEL ['High school' 'Middle school' 'Elementary school' 'Preschool']
CODIGO_METODOLOGIA ['Traditional Education' 'Accelerating Learning' 'Schoolized Preschool']
ANO_INF [2019 2020]
REPITENTE ['No' 'Yes']

In [60]:
categorias = list(set(categorias )- {'ANO_INF'})

In [65]:
for x in categorias:
    print( "'"+ x + "'" +": 'category'," )

'REPITENTE': 'category',
'computador': 'category',
'GENERO': 'category',
'embaraza': 'category',
'teneviv': 'category',
'ES_BILINGUE': 'category',
'DIR_NUM_LOCALIDAD': 'category',
'NIVEL': 'category',
'CODIGO_JORNADA': 'category',
'TIPO_DISCAPACIDAD': 'category',
'CODIGO_ETNIA': 'category',
'todos_servicios_Pub': 'category',
'PROVIENE_OTR_MUN': 'category',
'tiene_auto': 'category',
'POB_VICT_CONF': 'category',
'CAP_EXC': 'category',
'CODIGO_METODOLOGIA': 'category',

In [66]:
df['GENERO'] = df['GENERO'].astype('category')

<ipython-input-66-a355c1672eb1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['GENERO'] = df['GENERO'].astype('category')

In [69]:
df.to_csv('data/3-oro/DASH_concat_Valeira.csv')

In [74]:
t1 = pd.read_csv('data/3-oro/t19m.csv', index_col = 0)
t2 = pd.read_csv('data/3-oro/t19p.csv', index_col = 0)
t3 = pd.read_csv('data/3-oro/t19s.csv', index_col = 0)
t4 = pd.read_csv('data/3-oro/t20m.csv', index_col = 0)
t5 = pd.read_csv('data/3-oro/t20p.csv', index_col = 0)
t6 = pd.read_csv('data/3-oro/t20s.csv', index_col = 0)

In [75]:
t = pd.concat([t1,t2,t3,t4,t5,t6], axis = 0)

In [78]:
t.to_csv('data/3-oro/table_dash.csv')